SKILLS = {
    "python": ["python"],
    "java": ["java"],
    "c++": ["c++", "cpp"],
    "javascript": ["javascript", "js"],
    "react": ["react", "reactjs"],
    "node.js": ["node", "node.js", "express"],
    "django": ["django"],
    "flask": ["flask"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "data analysis": ["data analysis", "data analytics"],
    "nlp": ["nlp", "natural language processing"],
    "sql": ["sql", "mysql", "postgresql"],
    "mongodb": ["mongodb", "mongo"],
    "git": ["git", "github"],
    "docker": ["docker"],
    "aws": ["aws", "amazon web services"],
    "rest api": ["rest", "rest api", "apis"],
}
